import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Oddm-Campeonato de Golf",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children; // ✅ Apenas retorna children, sem <html> ou <body>
}